### ISSUE TITLE
Codemash-2020 Data

### ISSUE THREAD

**Issue by listba** [jameskbride/codemash-companion#29]
Hey James, do you have any intention/plan on updating the speaker / session list for Codemash 2020?

**Comment by jameskbride** [comment]
Hi Ben!  Thanks for your interest in the app.  I'd love to update it, unfortunately Codemash hasn't provided API endpoints this year. They previously used Sessionize to host this data, however they have an app of their own which is developed by a third party, and my suspicion is that they are pushing attendees towards that instead. 

I actually looked at unpublishing Codemash Companion to avoid confusion, but the Play store disallows this. I'm open to updating it if we find out that they actually do have an API however.
